#
# Makefile for the Goodix touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_ZTEMT_GT9XX_TOUCHSCREEN_DRIVER)	+= gt9xx.o
obj-$(CONFIG_ZTEMT_GT9XX_TOUCHSCREEN_UPDATE)	+= gt9xx_update.o
obj-$(CONFIG_ZTEMT_GT9XX_TOUCHSCREEN_DEBUG)     += goodix_tool.o
obj-$(CONFIG_ZTEMT_GT9XX_TOUCHSCREEN_TEST)      += gt9xx_openshort.o

